name: TMCTF
on: [push]
jobs: 
  Recon: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          env 
      - run: |
          ls -laR /home/
      - run: |
          rgrep -i "VE1DVEZ7" / 2>/dev/null

      - run: |
          rgrep -i "544d435446" / 2>/dev/null
      - run: |
          env && cat /home/*/bash_history &
